/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/city-gt.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1__13"].geometry}
        material={materials["1_1__13"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1_�"].geometry}
        material={materials.material_15}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1"].geometry}
        material={materials.material_16}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1001"].geometry}
        material={materials.material_3}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1002"].geometry}
        material={materials.material_4}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1003"].geometry}
        material={materials.material_5}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1004"].geometry}
        material={materials.material_6}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1005"].geometry}
        material={materials.material_7}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1006"].geometry}
        material={materials.material_8}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1007"].geometry}
        material={materials.material_9}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1008"].geometry}
        material={materials.material_11}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1009"].geometry}
        material={materials.material_12}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1010"].geometry}
        material={materials.material_17}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1011"].geometry}
        material={materials.material_18}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1012"].geometry}
        material={materials.material_19}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1013"].geometry}
        material={materials.material_20}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1014"].geometry}
        material={materials[".11_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1015"].geometry}
        material={materials[".6_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1016"].geometry}
        material={materials[".1_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1017"].geometry}
        material={materials[".5_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1018"].geometry}
        material={materials[".3_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1019"].geometry}
        material={materials[".2_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1020"].geometry}
        material={materials.material_27}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1021"].geometry}
        material={materials[".12_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1022"].geometry}
        material={materials[".10_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1023"].geometry}
        material={materials.material_30}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1024"].geometry}
        material={materials.material_31}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1025"].geometry}
        material={materials[".9_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1026"].geometry}
        material={materials.material_33}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1027"].geometry}
        material={materials.material_34}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1028"].geometry}
        material={materials.material_35}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1029"].geometry}
        material={materials.material_36}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1030"].geometry}
        material={materials[".14_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1031"].geometry}
        material={materials.material_38}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1032"].geometry}
        material={materials.material_39}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1033"].geometry}
        material={materials[".7_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1034"].geometry}
        material={materials[".8_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1035"].geometry}
        material={materials.material_42}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1036"].geometry}
        material={materials.material_43}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1037"].geometry}
        material={materials.material_44}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1038"].geometry}
        material={materials.material_45}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1039"].geometry}
        material={materials.material_46}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1040"].geometry}
        material={materials.material_47}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1041"].geometry}
        material={materials.material_48}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1042"].geometry}
        material={materials[".9_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1043"].geometry}
        material={materials.material_50}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1044"].geometry}
        material={materials[".13_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1045"].geometry}
        material={materials.material_52}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1046"].geometry}
        material={materials.material_53}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1047"].geometry}
        material={materials.material_54}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1048"].geometry}
        material={materials.material_55}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1049"].geometry}
        material={materials.material_56}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1050"].geometry}
        material={materials.material_57}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1051"].geometry}
        material={materials[".1_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1052"].geometry}
        material={materials.material_59}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1053"].geometry}
        material={materials.material_60}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1054"].geometry}
        material={materials[".13_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1055"].geometry}
        material={materials[".11_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1056"].geometry}
        material={materials[".10_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1057"].geometry}
        material={materials[".5_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1058"].geometry}
        material={materials[".7_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1059"].geometry}
        material={materials[".15_0"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1060"].geometry}
        material={materials[".3_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1061"].geometry}
        material={materials[".1_2"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1062"].geometry}
        material={materials[".8_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1063"].geometry}
        material={materials[".14_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1064"].geometry}
        material={materials[".2_1"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1065"].geometry}
        material={materials.material_14}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1066"].geometry}
        material={materials.material}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1067"].geometry}
        material={materials.material_10}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_1068"].geometry}
        material={materials[".2_2"]}
        position={[-3.722, 3.685, 48.666]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_�"].geometry}
        material={materials.material_15}
        position={[-63.039, 59.916, 28.398]}
        rotation={[0, -1.302, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_"].geometry}
        material={materials.material_16}
        position={[-63.039, 59.916, 28.398]}
        rotation={[0, -1.302, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1_001"].geometry}
        material={materials.material_17}
        position={[-63.039, 59.916, 28.398]}
        rotation={[0, -1.302, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["������������_������_1__0"].geometry}
        material={materials["1_1__13"]}
        position={[-63.039, 59.916, 28.398]}
        rotation={[0, -1.302, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/city-gt.glb");
